version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=test
  mongo-express:

    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin 
      - ME_CONFIG_BASICAUTH_PASSWORD=adminpass
volumes:
  data: {}

networks:
  default:
    name: mongodb_network